drop table Memberships cascade constraints;
drop table Passenger cascade constraints;
drop table Promotion cascade constraints;
drop table Airport cascade constraints;
drop table Airplane cascade constraints;
drop table Pilot cascade constraints;
drop table Luggage cascade constraints;
drop table LostLuggage cascade constraints;
drop table Booking cascade constraints;
drop table Cancellation cascade constraints;
drop table Refund cascade constraints;
drop table Payment cascade constraints;
drop table FlightSchedule cascade constraints;
drop table PilotSchedule cascade constraints;
drop table Ticket cascade constraints;
drop table Meal cascade constraints;
drop table Orderlist cascade constraints;
drop table Maintenance_Events cascade constraints;




CREATE TABLE Memberships(
        memberID                NUMBER(6)        GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        loyalty_points        NUMBER        NOT NULL,
        membership_lvl        NUMBER        NOT NULL
);




CREATE TABLE Passenger (
        passengerID NUMBER(6)  GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        memberID          NUMBER(6)         NOT NULL,
        name                 VARCHAR(25)NOT NULL, 
        phone                 VARCHAR(12)NOT NULL,
        nationality VARCHAR(25)NOT NULL, 
        dob                 DATE                 NOT NULL,
        passportNum VARCHAR(10) NOT NULL, 
        email                 VARCHAR(30)NOT NULL,
        sex                 VARCHAR(6) NOT NULL,
        age                 NUMBER(3)         NOT NULL,
        CONSTRAINT memberIDCheck FOREIGN KEY(memberID) REFERENCES Memberships(memberID),
        CONSTRAINT         phoneNumberCheck
        CHECK (REGEXP_LIKE(phone, '^\d{3}\d{7,8}$')),
        CONSTRAINT         emailCheck
        CHECK (REGEXP_LIKE(email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$'))
);


CREATE TABLE Promotion (
        promotionID        NUMBER(6)          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        rate                         NUMBER(2,2) NOT NULL,
        startDate                 DATE                  NOT NULL,
        expiryDate         DATE                  NOT NULL,
        promotionName                VARCHAR(20) NOT NULL,
        CONSTRAINT      expiryDateCheck
        CHECK (expiryDate >= startDate)
);


CREATE TABLE Airport(
        airportID         NUMBER(6)         GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        name                VARCHAR(20) NOT NULL,
        city                VARCHAR(30) NOT NULL
);


CREATE TABLE Airplane(
        airplaneID         NUMBER(6)            GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        model               VARCHAR(5)     NOT NULL,
        capacity                NUMBER(2)            NOT NULL,
        class                        VARCHAR(25)    NOT NULL
);


CREATE TABLE Pilot (
        pilotID         NUMBER(6)          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        firstName         VARCHAR(25) NOT NULL,
        lastName         VARCHAR(25) NOT NULL,
        licenceNo         NUMBER(9) NOT NULL,
        rank                 VARCHAR(25) NOT NULL,
        salary        NUMBER(6) NOT NULL
);




CREATE TABLE Booking(
        bookingID                NUMBER(6)                GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        promotionID          NUMBER(6)                , 
        passengerID        NUMBER(6)                NOT NULL,
        numOfPassenger        NUMBER(2)                NOT NULL,
        bookingDate        DATE                        NOT NULL,
        bookingTime        TIMESTAMP                NOT NULL,
        status                VARCHAR(15)        NOT NULL,
        CONSTRAINT promotionIDCheck FOREIGN KEY(promotionID) REFERENCES Promotion(promotionID),
        CONSTRAINT passengerIDCheck FOREIGN KEY(passengerID) REFERENCES Passenger(passengerID)
);




CREATE TABLE Meal(
        mealID                NUMBER(6)                GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        name         Varchar(30)                NOT NULL, 
        price        NUMBER(6,2)                NOT NULL,
        category        Varchar(20)                NOT NULL,
        quantityInStock        NUMBER(2)                        NOT NULL
);




CREATE TABLE Orderlist(
        bookingID                NUMBER(6)        NOT NULL,
        mealID         NUMBER(6)                NOT NULL, 
        quantity        NUMBER(6)                NOT NULL,
        totalPrice        NUMBER(2)                NOT NULL,
        PRIMARY KEY(bookingID, mealID),
        CONSTRAINT bookingIDCheck5 FOREIGN KEY(bookingID) REFERENCES Booking( bookingID),
        CONSTRAINT mealIDCheck FOREIGN KEY(mealID) REFERENCES Meal(mealID)
);




CREATE TABLE Luggage(
        luggageID                NUMBER(6)        GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        bookingID        NUMBER(6)        NOT NULL, 
        airplaneID                NUMBER(6)        NOT NULL, 
        weight                NUMBER(6,2)NOT NULL, 
        status                 VARCHAR(20)NOT NULL,
        checkIn_date        DATE        ,
        checkIn_time        TIMESTAMP        ,
        unit                         NUMBER(2)        NOT NULL, 
        CONSTRAINT bookingIDCheck3 FOREIGN KEY(bookingID) REFERENCES Booking(bookingID),
        CONSTRAINT airplaneIDCheck3 FOREIGN KEY(airplaneID) REFERENCES Airplane(airplaneID)
);


CREATE TABLE LostLuggage(
        reportID        NUMBER(6)        GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        luggageID         NUMBER(6)        NOT NULL, 
        unit                 NUMBER(2)        NOT NULL,
        reportDateTime        TIMESTAMP                 NOT NULL, 
        status         VARCHAR(20) NOT NULL,
        CONSTRAINT luguageIDCheck FOREIGN KEY(luggageID) REFERENCES Luggage(luggageID)
);


CREATE TABLE Cancellation (
        cancellationID         NUMBER(6)         GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        bookingID                NUMBER(6)         NOT NULL, 
        cancelDate                DATE                  NOT NULL,
        cancelReason        VARCHAR(25) NOT NULL,
        CONSTRAINT bookingIDCheck FOREIGN KEY(bookingID) REFERENCES Booking(bookingID)
);


CREATE TABLE Refund (
        refundID                 NUMBER(6)          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        cancellationID        NUMBER(6)         NOT NULL,
        refundDate         DATE                  NOT NULL,
        refundAmount         NUMBER(8,2) NOT NULL,
        CONSTRAINT cancellationIDCheck FOREIGN KEY(cancellationID) REFERENCES Cancellation(cancellationID)
);


CREATE TABLE Payment (
        paymentID                 NUMBER(6)          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        bookingID                NUMBER(6)         NOT NULL,
        totalAmount         NUMBER(8,2) NOT NULL,
        method                 VARCHAR(25) NOT NULL,
        paymentDate         DATE                  NOT NULL,
paymentTime        TIMESTAMP                NOT NULL,
        CONSTRAINT bookingIDCheck2 FOREIGN KEY(bookingID) REFERENCES Booking(bookingID),
        CONSTRAINT      totalAmount
        CHECK (totalAmount > 0)
);


CREATE TABLE Maintenance_Events (
    eventID        NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    airplaneID     NUMBER(6) NOT NULL,             
    eventDate      DATE NOT NULL,                  
    eventType      VARCHAR(50) NOT NULL,           
    cost           NUMBER(10,2) NOT NULL,          
    downtime_days  NUMBER(3),
    CONSTRAINT airplaneIDCheck FOREIGN KEY(airplaneID) REFERENCES Airplane(airplaneID)
);


CREATE TABLE FlightSchedule(
   flightScheduleID      NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
   airplaneID            NUMBER(6)       NOT NULL,
   departureAirportID             NUMBER(2)       NOT NULL,
   arrivalAirportID             NUMBER(2)       NOT NULL,
   departureDateTime         TIMESTAMP       NOT NULL,
   arrivalDateTime           TIMESTAMP            NOT NULL,
   status                VARCHAR(25)     NOT NULL,
   CONSTRAINT airplaneIDCheck2 FOREIGN KEY(airplaneID) REFERENCES Airplane(airplaneID),
   CONSTRAINT departureAirportIDCheck2 FOREIGN KEY(departureAirportID) REFERENCES Airport(AirportID),
  CONSTRAINT arrivalAirportIDCheck2 FOREIGN KEY(arrivalAirportID) REFERENCES Airport(AirportID),
   CONSTRAINT arrivalTimeCheck
   CHECK (arrivalDateTime > departureDateTime)
);


CREATE TABLE PilotSchedule(
        flightScheduleID         NUMBER(6)        NOT NULL,
        pilotID                         NUMBER(6)        NOT NULL, 
        position                        VARCHAR(20)NOT NULL,
        status                        VARCHAR(20)NOT NULL,
        PRIMARY KEY(flightScheduleID, pilotID),
        CONSTRAINT flightScheduleIDCheck FOREIGN KEY(flightScheduleID) REFERENCES FlightSchedule(flightScheduleID),
        CONSTRAINT pilotIDCheck FOREIGN KEY(pilotID) REFERENCES Pilot(pilotID)
);


CREATE TABLE Ticket(
        ticketID                NUMBER(6)          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        bookingID                        NUMBER(6)         NOT NULL,
        flightScheduleID         NUMBER(6)         NOT NULL, 
        seatNum                        VARCHAR(4)         NOT NULL, 
        price                        NUMBER(6)        NOT NULL,
        date_of_Issue                DATE                 NOT NULL,
        boardingTime                TIMESTAMP         NOT NULL,
        gate                                VARCHAR(3)         NOT NULL, 
        CONSTRAINT bookingIDCheck4 FOREIGN KEY(bookingID) REFERENCES Booking(bookingID),
        CONSTRAINT flightScheduleIDCheck2 FOREIGN KEY(flightScheduleID) REFERENCES FlightSchedule(flightScheduleID)
);